#!/bin/sh -e

HERE=$(dirname $(readlink -f $0))
cd $HERE

if [ -z $VENV ] ; then
	VENV=$(mktemp -d)
	trap rm -rf $VENV EXIT
fi
if [ ! -d $VENV ] ; then
	python3 -m venv $VENV
	$VENV/bin/pip3 install requests black mypy
fi

$VENV/bin/black --quiet --check ./
$VENV/bin/mypy ./
